### ISSUE TITLE
Update buildroot to fix package download URL

### ISSUE THREAD

**Issue by YaxelFulfil** [embeddedTS/buildroot-ts#38]
The website to download pkgconf sources is down because the domain name dereferenced.org was stolen. See https://github.com/pkgconf/pkgconf/issues/302. [This commit](https://git.busybox.net/buildroot/commit/package/pkgconf/pkgconf.mk?id=ef95ec920cbae32e5a525d887b7a279440d96f11) fixes the issue.

**Comment by ts-kris** [comment]
Thank you for bringing this to our attention, I hadn't seen this yet.

First, this is a tricky bug because we cannot directly do anything about it. As this repo is a br2-external tree using upstream Buildroot as a submodule, we can't cherry-pick patches in. We try to really only match upstream release tags and test our defconfigs and platforms against those.

Second, none of our default configs, including our `extra_packages_defconfig`, use `pkgconf` by default. So our defaults are not directly affected.

However, I have a few suggestions/workarounds that anyone affected by this issue can attempt. See below.

I will leave this issue open and keep an eye on the upstream bug. Once a release rolls through with the fix and the Buildroot submodule is not affected by this issue, I will close this issue. So, as long as this issue is open open and you need `pkgconf`, then take a look at the workarounds below.

## Workarounds
### Option 1: Update Buildroot submodule to cherry-pick in the fixed URL commit from upstream
As the `buildroot/` directory is just a submodule, it is possible to update to a specific branch, commit, etc., and be able to use that in conjunction with our br2-external tree. Due to how submodules works, cherry-picking in a commit creates a new commit hash in the submodule that would not actually exist in its remote repository. Because of this, we cannot just cherry-pick in the commit and push that change since the referenced hash wouldn't exist in Buildroot remote. To cherry-pick the URL update commit in to the Buildroot subproject:
```
cd buildroot/
git cherry-pick ef95ec920cbae32e5a525d887b7a279440d96f11
cd -
```
From there, re-issue the `make <platform>_defconfig` command to rebuild the working configuration against the updated Buildroot tree. This process will allow for just pulling in the fix. However, this may not be viable for some users/applications that may require all sources used have traceable commit hashes as now the cherry-picked commit would only exist in this one location.


### Option 2: Update Buildroot submodule to the latest HEAD to pull in this change.
As the `buildroot/` directory is just a submodule, it is possible to update to a specific branch, commit, etc., and be able to use that in conjunction with our br2-external tree. To update the submodule to the `master` branch, for example:
```
cd buildroot
git checkout master
cd -
```
From there, re-issue the `make <platform>_defconfig` command to rebuild the working configuration against the updated Buildroot tree. As of this moment, the `master` branch of Buildroot contains the updated URL for `pkgconf`. Note that this may cause other issues as there are a good number of updates between the current tag used in this project and the current `HEAD` of Buildroot.

This is always possible for any users wanting to get the latest Buildroot release to use with our br2-external tree. The only downside is any conflicts may need to be resolved and we would not have done any testing on this. We only do testing against commits we put in this repository directly.


### Option 3: For host_pkgconf need only
If the build process only requires host_pkgconf, then it should be possible to simply install `pkgconf` on the host Linux workstation that is actually building the Buildroot image. This may not always be possible, as some packages may force the inclusion of `BR2_PACKAGE_HOST_PKGCONF` and you would still be stuck with Buildroot attempting to download from an invalid URL.
